"""Add video url

Revision ID: af6287d401b7
Revises: c9cda4d03ae0
Create Date: 2023-02-17 12:23:57.190640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6287d401b7'
down_revision = 'c9cda4d03ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('dollar_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('dollar_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
